language: c
os: linux

compiler: gcc

install:
        - sudo apt-get update
        - sudo apt-get install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf qemu-user qemu-system build-essential git-core

script:
        # lab-1
        - cd lab-1
        - git submodule foreach git pull origin master
        - make
        - make doTest
        - cd ..
